spring:
  datasource:
    url: jdbc:postgresql://ep-calm-bush-a6byxev5-pooler.us-west-2.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_Gq1b2jZHEchv
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

server:
  port: 3030
